### ISSUE TITLE
In-app downloader issue

### ISSUE THREAD

**Issue by ilyassesalama** [abdulrahmanMostafa30/EgyBestBot#12]
The internal downloader has 2 issues. The first is as mentioned in the screenshot "failed to merge segment", and the second issue is file naming. When you download an entire series, all episodes have the same name, which causes the episodes to overwrite each other.

![image](https://user-images.githubusercontent.com/46769766/197224702-0229fb2d-01d0-437b-aa84-cf5df15aa238.png)

**Comment by abdelrahman30x** [comment]
The names of the episodes are different
Even if it has the same name, before it downloads the other episode, it deletes any old files ( temp downloaded folder )
I will try to check for more episodes  , if there are problems I will tell you

![image](https://user-images.githubusercontent.com/52821000/197262689-5c0caa5e-24db-4100-8f74-6395beacd8f7.png)

**Comment by abdelrahman30x** [comment]
The program downloads normally series

![Screenshot 2022-10-22 144251](https://user-images.githubusercontent.com/52821000/197357871-759ad326-cb5c-4381-ba95-a11dbdad4bb0.jpg)

If you mean the same names that I marked

![image](https://user-images.githubusercontent.com/52821000/197357995-fc17f323-2b7c-4319-8336-7f08d077638e.png)

It splits the file into 16 files so that it can be downloaded at the same time and then they are merged at the end
I don't know why you're error , but it's permission denied
You can try again or try with Run as Administrator mode 

Try and tell me
