### ISSUE TITLE
Window Resolution Ptoblem

### ISSUE THREAD

**Issue by bahaedin** [abdulrahmanMostafa30/EgyBestBot#18]
the window does not seem to be displayed correctly I have a 1080p screen.

1. I'm on the latest version available **1.26**
2. I tried to modify the CMD resolution but the problem still exists, I didn't have this problem before with the old version!

![Screenshot (3)](https://user-images.githubusercontent.com/57917164/209471929-87c3f697-544d-4871-9097-9d0977c3ef7f.png)

**thank you for this wonderful software**

**Comment by abdelrahman30x** [comment]
My pleasure 🖤

The problem is that I am trying to adjust the windows according to the properties of the users screen

Not only screen resolution, but cmd font type and font size for each user

All this to show data (series , movie , ....  ) in table depending on screen size , font type ,  font size😅

ex:
![Screenshot 2022-12-26 053043](https://user-images.githubusercontent.com/52821000/209496463-95749c12-7336-4a0d-87da-b193e00c7a5a.jpg)

What happens if the line is larger than the screen size?

The line is backwards

Anway , try update to 1.27

I tried another way to change the font type and size

**Comment by bahaedin** [comment]
I would like to thank you my brother @abdulrahmanMostafa30  for your support and your efforts to develop this program.
The problem has been **solved** with the new version **1.27**.

![Screenshot (4)](https://user-images.githubusercontent.com/57917164/209613369-8887f952-9b93-425e-ad5f-f391e8118659.png)
