### ISSUE TITLE
No Internet Connection , Try after 2s

### ISSUE THREAD

**Issue by CrcakOnDemand** [abdulrahmanMostafa30/EgyBestBot#5]
without VPN
Every time I open the program I get an error message "No Internet Connection , Try after 2s"

**Comment by abdelrahman30x** [comment]
using snifing ?
if not , send screen from egybset any browser
be sure not using vpn

**Comment by abdelrahman30x** [comment]
Because the problem you had was because of the ban from isp.

I added the option to specify a working link for EGYBEST <a href="https://github.com/abdulrahmanMostafa30/EgyBestBot/releases/tag/1.6">1.6</a>.

The program into to https://www.egy.best/
Then it is redirected to another link to avoid being banned. The redirected link may also be banned
This problem is temporary because the domain is changed a lot from egybest
I will close the issue.
